security:
    encoders: 
        App\Entity\User:
            algorithm: bcrypt
    
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
                pattern: ^/admin
                anonymous: lazy
                provider: in_database
                form_login:
                    login_path: admin_account_login
                    check_path : admin_account_login 
                    default_target_path: /admin
                    always_use_default_target_path: true
                    use_referer: true
                    
                logout:
                    path: admin_account_logout
                    target: admin_account_login 
    
                user_checker: App\Security\UserEnabledChecker                  
        main:
            anonymous: lazy

            provider: in_database
            form_login:
               login_path: account_login
               check_path: account_login
               default_target_path: home 
               always_use_default_target_path: true
               use_referer: true
               
            logout:
                path: account_logout
                target: account_login    

            user_checker: App\Security\UserEnabledChecker

    access_control:
         - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
      
    role_hierarchy:
            ROLE_WRITER: ROLE_USER
            ROLE_ADMIN: [ROLE_WRITER, ROLE_EDITER]
            ROLE_SUPERADMIN: ROLE_ADMIN